### ISSUE TITLE
Has the data been split into segments for pretraining

### ISSUE THREAD

**Issue by rakshanda22** [zihangdai/xlnet#57]
The paper says  

> During the pretraining phase, following BERT, we randomly sample two segments (either from the same context or not) and treat the concatenation of two segments as one sequence to perform permutation language modeling. 

I don't really get this, if there is no next sentence prediction what is the point of concatenating segments that do not belong to the same context? Won't that degrade the performance of the model? What is the objective behind using two segments (both from the same context and not)?

**Comment by kimiyoung** [comment]
The motivation is that the model sees multiple segments during the pretraining phase, which is more consistent with finetuning.

**Comment by rakshanda22** [comment]
@kimiyoung Thanks I got it!

**Comment by shaform** [comment]
Hi,

I am still confused about the objective when segments exist:

Does the permutation objective simply treat the following sequence as if there are no segments and therefore the `[SEP]`, `[CLS]` can sometimes be the target being predicted?

[A, SEP, B, SEP, CLS]

For example, assume both `A` and `B` has length `1`.
One possible factorization would be

```
p(x) = p(SEP_1)p(CLS|SEP_1)p(B|CLS,SEP_1)p(A|B,CLS,SEP_1)p(SEP_2|A,B,CLS,SEP_1)
```

Then, since `SEP_2` is the last token in this order, the objective would try to maximize `p(SEP_2|A,B,CLS,SEP_1)`.

Is this correct?


Also, are there any differences in terms of objective for the following two different cases?
(1) segment A and B are from the same context.
(2) segment A and B are from different context.
